### ISSUE TITLE
Create multiple account across circle

### ISSUE THREAD

**Issue by mirzahimami** [Zersya/inving-money-tracker#28]
I want to create account for my circle. For example: Account for BCA, Account for ShopeePay, Account for Jago. Each account have their transaction and circle will accumulate all the income from all account.

**Comment by Zersya** [comment]
@mirzahimami We have an 'Account' under 'Assets' classified as 'Cash and Cash Equivalents (CCE)', which remains constant regardless of transaction records. What's your opinion on this? do you need it to be dynamically increase and decrease based on the transaction records? we have plan to do that in the near time

![CleanShot 2023-08-28 at 16 56 37@2x](https://github.com/Zersya/inving-money-tracker/assets/11307389/3ffafb9c-09f4-4558-910c-0f287ca81c08)

**Comment by mirzahimami** [comment]
It's kind of like that and yes I need to know my cash flow from my each assets. It will have 3 categories : Income, Expense, Transfer. For transfer it will just count as moving my money from another assets. Transfer sometimes will have fee and it will count as expense.

**Comment by Zersya** [comment]
hi @mirzahimami I'm sorry with the late response and progress, please kinda check the preview mode at #45 and it will be our pleasure if you give some feedback on that. 😊
thanks.
