### ISSUE TITLE
Currency format when fill amount

### ISSUE THREAD

**Issue by mirzahimami** [Zersya/inving-money-tracker#34]
![image](https://github.com/Zersya/inving-money-tracker/assets/108782040/40d20e54-a0c9-4d33-91d8-438150a56ce5)

I want my amount to be currency format while I fill the field not after I finish fill the field.

**Comment by Zersya** [comment]
Okay, this is on my plan in the future, but I think we can do it on release v0.1.0.

**Comment by Zersya** [comment]
Hey @mirzahimami, I've submitted a PR. I'll suggest you could check the result on [preview deployment](https://inving-money-tracker-git-34-currency-format-when-dea8be-zersya.vercel.app/)
