### ISSUE TITLE
Income as type transaction

### ISSUE THREAD

**Issue by mirzahimami** [Zersya/inving-money-tracker#55]
I want income as type of transaction instead of category. Because I need to select either expenses or transfer even thought that was different from income.

![image](https://github.com/Zersya/inving-money-tracker/assets/108782040/3a808e22-5bc7-45f7-a5ca-480f4cb9133b)

**Comment by Zersya** [comment]
The type is not an attributes on database, it’s just an action to create a different form between create records or transfer amount of assets.

I think the **Expenses type** need to be rename to be something like **Records**.

**Comment by Zersya** [comment]
Update pushed 230baced38cecdd35904d7fe49b6ec8b15994c32
