### ISSUE TITLE
Transfer Record

### ISSUE THREAD

**Issue by mirzahimami** [Zersya/inving-money-tracker#56]
I need to record my transfer in transaction
![image](https://github.com/Zersya/inving-money-tracker/assets/108782040/b4cf9e7f-d2e3-4384-8b17-ee61f94ed6d3)

**Comment by mirzahimami** [comment]
I know we have this in history, but I need to know my transfer record also in transaction.
![image](https://github.com/Zersya/inving-money-tracker/assets/108782040/4ea7a1fe-9f07-4696-9f19-f8d3501d5e0d)

**Comment by Zersya** [comment]
Before the development process back then, we also thought that it need to be visible on the list, do you need toggle to make it hide on the list quickly?

**Comment by Zersya** [comment]
@mirzahimami feel free to check the new features 🚀
