### ISSUE TITLE
Fee from transfer

### ISSUE THREAD

**Issue by mirzahimami** [Zersya/inving-money-tracker#57]
Sometimes I will have fee after transfer between my assets. I need to add that as expense and I want my fee to be included in this form transaction.
![image](https://github.com/Zersya/inving-money-tracker/assets/108782040/a16e8345-9284-4f87-9f4c-bdd8bc1fd8b1)

**Comment by Zersya** [comment]
That’s kinda make sense, it’s like an optional field below the amount ya.
